export const routes = {
  home: "/",
  auth: "/auth",
  login: "/auth/login",
  signup: "/auth/signup",
  dashboard: "/dashboard",
  dashboardAdmin: "/dashboard/admin",
  dashboardProfile: "/dashboard/profile",
  dashboardRequests: "/dashboard/requests",
  dashboardSettings: "/dashboard/settings",
  nearby: "/nearby",
  books: "/books",
  bookDetail: (bookId: string) => `/books/${bookId}`,
  nearbyBooks: (bookId: string) => `/books/${bookId}/nearby`,
  newBook: "/dashboard/books/new",
  editBook: (bookId: string) => `/dashboard/books/${bookId}/edit`,
} as const;
